program LclSnapshotTest;

{$mode objfpc}{$H+}

uses
  Interfaces, // LCL widgetset initialization
  Classes, SysUtils, Graphics, Forms,
  rpreport, rpmetafile, rplcldriver, rppreviewcontrol, rppreviewmetalcl, rplclpreview;

function FindReportFile(const AFileName: string): string;
var
  candidates: array[0..3] of string;
  i: Integer;
begin
  candidates[0] := AFileName;
  candidates[1] := '..' + PathDelim + '..' + PathDelim + '..' + PathDelim + 'repman' + PathDelim + 'repsamples' + PathDelim + AFileName;
  candidates[2] := 'C:\desarrollo\prog\toni\reportman\repman\repsamples\' + AFileName;
  candidates[3] := '/mnt/c/desarrollo/prog/toni/reportman/repman/repsamples/' + AFileName;

  for i := 0 to High(candidates) do
  begin
    if (candidates[i] <> '') and FileExists(candidates[i]) then
      Exit(candidates[i]);
  end;
  Result := AFileName;
end;

function TestSnapshot(const ARepFileName, AOutPng: string; AScale: Double = 1.0): Boolean;
var
  repPath: string;
  report: TRpReport;
  driver: TRpGDIDriver;
  png: TPortableNetworkGraphic;
  pageCount, i: Integer;
begin
  Result := False;
  repPath := FindReportFile(ARepFileName);

  WriteLn('--------------------------------------------------');
  WriteLn('Testing LCL Snapshot for: ', ARepFileName, ' Scale: ', AScale:0:2);
  WriteLn('Report path             : ', repPath);
  WriteLn('Output snapshot PNG     : ', AOutPng);
  WriteLn('--------------------------------------------------');

  if not FileExists(repPath) then
  begin
    WriteLn('ERROR: Report file not found: ', repPath);
    Exit;
  end;

  if FileExists(AOutPng) then
    DeleteFile(AOutPng);

  report := TRpReport.Create(nil);
  try
    try
    WriteLn('1. Loading report definition...');
    report.LoadFromFile(repPath);

    WriteLn('2. Initializing TRpGDIDriver (LCL engine)...');
    driver := TRpGDIDriver.Create;
    try
      driver.Scale := AScale;
      WriteLn('3. Calling report.BeginPrint...');
      report.BeginPrint(driver);

      WriteLn('4. Requesting first page...');
      report.Metafile.RequestPage(1);
      pageCount := report.Metafile.CurrentPageCount;
      WriteLn('   CurrentPageCount = ', pageCount);

      if pageCount < 1 then
      begin
        WriteLn('ERROR: No pages generated by report engine.');
        Exit;
      end;

      WriteLn('--- Dumping Page 0 Objects (total: ', report.Metafile.Pages[0].ObjectCount, ') ---');
      for i := 0 to report.Metafile.Pages[0].ObjectCount - 1 do
      begin
        WriteLn(Format('Obj %3d: Type=%d L=%5d T=%5d W=%5d H=%5d', [
          i,
          Integer(report.Metafile.Pages[0].Objects[i].MetaType),
          report.Metafile.Pages[0].Objects[i].Left,
          report.Metafile.Pages[0].Objects[i].Top,
          report.Metafile.Pages[0].Objects[i].Width,
          report.Metafile.Pages[0].Objects[i].Height
        ]));
        if report.Metafile.Pages[0].Objects[i].MetaType = rpMetaText then
          WriteLn('         Text: "', report.Metafile.Pages[0].GetText(report.Metafile.Pages[0].Objects[i]), '"');
      end;
      WriteLn('--------------------------------------------------');

      WriteLn('5. Rendering Page 0 onto LCL TBitmap Canvas via TRpGDIDriver.DrawPage...');
      driver.NewDocument(report.Metafile, 1, false);
      driver.DrawPage(report.Metafile.Pages[0]);

      if not Assigned(driver.bitmap) then
      begin
        WriteLn('ERROR: driver.bitmap is nil after DrawPage.');
        Exit;
      end;

      WriteLn('   Rendered bitmap size: ', driver.bitmap.Width, 'x', driver.bitmap.Height);

      WriteLn('6. Saving to PNG snapshot file...');
      png := TPortableNetworkGraphic.Create;
      try
        png.Assign(driver.bitmap);
        png.SaveToFile(AOutPng);
      finally
        png.Free;
      end;

      report.EndPrint;
    finally
      driver.Free;
    end;

    if FileExists(AOutPng) then
    begin
      WriteLn('SUCCESS: Snapshot PNG created: ', AOutPng);
      Result := True;
    end
    else
      WriteLn('ERROR: File was not created: ', AOutPng);

    except
      on E: Exception do
      begin
        WriteLn('ERROR in TestSnapshot(', ARepFileName, '): [', E.ClassName, '] ', E.Message);
        WriteLn(BackTraceStrFunc(ExceptAddr));
        for i := 0 to ExceptFrameCount - 1 do
          WriteLn(BackTraceStrFunc(ExceptFrames[i]));
      end;
    end;
  finally
    report.Free;
  end;
end;

function TestPreviewFormInstantiation: Boolean;
var
  previewForm: TFRpVPreview;
begin
  Result := False;
  WriteLn('--------------------------------------------------');
  WriteLn('Testing TFRpVPreview Form Instantiation');
  WriteLn('--------------------------------------------------');
  try
    previewForm := TFRpVPreview.Create(nil);
    try
      WriteLn('1. TFRpVPreview instantiated successfully.');
      WriteLn('   Title: ', previewForm.Caption);
      WriteLn('   Width: ', previewForm.Width, ', Height: ', previewForm.Height);
      Result := True;
    finally
      previewForm.Free;
    end;
    WriteLn('2. TFRpVPreview destroyed cleanly.');
  except
    on E: Exception do
      WriteLn('ERROR during TFRpVPreview instantiation: ', E.Message);
  end;
end;

var
  passed, total: Integer;
begin
  Application.Initialize;

  passed := 0;
  total := 0;

  Inc(total);
  if TestSnapshot('firedactest.rep', 'snapshot_firedactest.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('sample4.rep', 'snapshot_sample4.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('bold.rep', 'snapshot_bold.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold.png', 1.0) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_110.png', 1.1) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_090.png', 0.9) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_050.png', 0.5) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_150.png', 1.5) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_200.png', 2.0) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('arab2wordwrap.rep', 'snapshot_arab2wordwrap.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('htmltest.rep', 'snapshot_htmltest.png') then
    Inc(passed);

  Inc(total);
  if TestPreviewFormInstantiation then
    Inc(passed);

  WriteLn('==================================================');
  WriteLn(Format('LCL Visual Test Results: %d / %d PASSED', [passed, total]));
  WriteLn('==================================================');

  if passed = total then
    Halt(0)
  else
    Halt(1);
end.
