program LclSnapshotTest;

{$mode objfpc}{$H+}

uses
  Interfaces, // LCL widgetset initialization
  Classes, SysUtils, Graphics, Forms,
  rpreport, rpmetafile, rplcldriver, rppreviewcontrol, rppreviewmetalcl, rplclpreview, rppdfdriver;

function FindReportFile(const AFileName: string): string;
var
  candidates: array[0..2] of string;
  i: Integer;
begin
  candidates[0] := AFileName;
  candidates[1] := '..' + PathDelim + '..' + PathDelim + '..' + PathDelim + 'repman' + PathDelim + 'repsamples' + PathDelim + AFileName;
  // tests/fpc/LclSnapshotTest/<exe> -> repo root is three levels up from the executable
  candidates[2] := ExtractFilePath(ParamStr(0)) + '..' + PathDelim + '..' + PathDelim + '..' + PathDelim + 'repman' + PathDelim + 'repsamples' + PathDelim + AFileName;

  for i := 0 to High(candidates) do
  begin
    if (candidates[i] <> '') and FileExists(candidates[i]) then
      Exit(candidates[i]);
  end;
  Result := AFileName;
end;

function TestSnapshot(const ARepFileName, AOutPng: string; AScale: Double = 1.0): Boolean;
var
  repPath: string;
  report: TRpReport;
  driver: TRpGDIDriver;
  png: TPortableNetworkGraphic;
  pageCount, i: Integer;
begin
  Result := False;
  repPath := FindReportFile(ARepFileName);

  WriteLn('--------------------------------------------------');
  WriteLn('Testing LCL Snapshot for: ', ARepFileName, ' Scale: ', AScale:0:2);
  WriteLn('Report path             : ', repPath);
  WriteLn('Output snapshot PNG     : ', AOutPng);
  WriteLn('--------------------------------------------------');

  if not FileExists(repPath) then
  begin
    WriteLn('ERROR: Report file not found: ', repPath);
    Exit;
  end;

  if FileExists(AOutPng) then
    DeleteFile(AOutPng);

  report := TRpReport.Create(nil);
  try
    try
    WriteLn('1. Loading report definition...');
    report.LoadFromFile(repPath);

    WriteLn('2. Initializing TRpGDIDriver (LCL engine)...');
    driver := TRpGDIDriver.Create;
    try
      driver.Scale := AScale;
      WriteLn('3. Calling report.BeginPrint...');
      report.BeginPrint(driver);

      WriteLn('4. Requesting first page...');
      report.Metafile.RequestPage(1);
      pageCount := report.Metafile.CurrentPageCount;
      WriteLn('   CurrentPageCount = ', pageCount);

      if pageCount < 1 then
      begin
        WriteLn('ERROR: No pages generated by report engine.');
        Exit;
      end;

      WriteLn('--- Dumping Page 0 Objects (total: ', report.Metafile.Pages[0].ObjectCount, ') ---');
      for i := 0 to report.Metafile.Pages[0].ObjectCount - 1 do
      begin
        WriteLn(Format('Obj %3d: Type=%d L=%5d T=%5d W=%5d H=%5d', [
          i,
          Integer(report.Metafile.Pages[0].Objects[i].MetaType),
          report.Metafile.Pages[0].Objects[i].Left,
          report.Metafile.Pages[0].Objects[i].Top,
          report.Metafile.Pages[0].Objects[i].Width,
          report.Metafile.Pages[0].Objects[i].Height
        ]));
        if report.Metafile.Pages[0].Objects[i].MetaType = rpMetaText then
          WriteLn('         Text: "', report.Metafile.Pages[0].GetText(report.Metafile.Pages[0].Objects[i]), '"');
      end;
      WriteLn('--------------------------------------------------');

      WriteLn('5. Rendering Page 0 onto LCL TBitmap Canvas via TRpGDIDriver.DrawPage...');
      driver.NewDocument(report.Metafile, 1, false);
      driver.DrawPage(report.Metafile.Pages[0]);

      if not Assigned(driver.bitmap) then
      begin
        WriteLn('ERROR: driver.bitmap is nil after DrawPage.');
        Exit;
      end;

      WriteLn('   Rendered bitmap size: ', driver.bitmap.Width, 'x', driver.bitmap.Height);

      WriteLn('6. Saving to PNG snapshot file...');
      png := TPortableNetworkGraphic.Create;
      try
        png.Assign(driver.bitmap);
        png.SaveToFile(AOutPng);
      finally
        png.Free;
      end;

      report.EndPrint;
    finally
      driver.Free;
    end;

    if FileExists(AOutPng) then
    begin
      WriteLn('SUCCESS: Snapshot PNG created: ', AOutPng);
      Result := True;
    end
    else
      WriteLn('ERROR: File was not created: ', AOutPng);

    except
      on E: Exception do
      begin
        WriteLn('ERROR in TestSnapshot(', ARepFileName, '): [', E.ClassName, '] ', E.Message);
        WriteLn(BackTraceStrFunc(ExceptAddr));
        for i := 0 to ExceptFrameCount - 1 do
          WriteLn(BackTraceStrFunc(ExceptFrames[i]));
      end;
    end;
  finally
    report.Free;
  end;
end;

function TestPreviewFormInstantiation: Boolean;
var
  previewForm: TFRpVPreview;
begin
  Result := False;
  WriteLn('--------------------------------------------------');
  WriteLn('Testing TFRpVPreview Form Instantiation');
  WriteLn('--------------------------------------------------');
  try
    previewForm := TFRpVPreview.Create(nil);
    try
      WriteLn('1. TFRpVPreview instantiated successfully.');
      WriteLn('   Title: ', previewForm.Caption);
      WriteLn('   Width: ', previewForm.Width, ', Height: ', previewForm.Height);
      Result := True;
    finally
      previewForm.Free;
    end;
    WriteLn('2. TFRpVPreview destroyed cleanly.');
  except
    on E: Exception do
      WriteLn('ERROR during TFRpVPreview instantiation: ', E.Message);
  end;
end;

function TestMetafileExportPDFAndPNG: Boolean;
var
  repPath: string;
  report: TRpReport;
  driver: TRpGDIDriver;
  pdfFile, pngFile: string;
  count: Integer;
  fs: TFileStream;
  buf: array[0..3] of Byte;
  sr: TSearchRec;
begin
  Result := False;
  WriteLn('--------------------------------------------------');
  WriteLn('Testing Metafile Export to PDF A/3 and PNG');
  WriteLn('--------------------------------------------------');
  repPath := FindReportFile('boldold.rep');
  if not FileExists(repPath) then
  begin
    WriteLn('ERROR: Report file not found: ', repPath);
    Exit;
  end;

  report := TRpReport.Create(nil);
  try
    report.LoadFromFile(repPath);
    driver := TRpGDIDriver.Create;
    try
      report.BeginPrint(driver);
      report.Metafile.RequestPage(1);

      pdfFile := 'test_export_boldold_a3.pdf';
      if FileExists(pdfFile) then DeleteFile(pdfFile);

      WriteLn('1. Exporting metafile to PDF A/3 via SaveMetafileToPDF...');
      SaveMetafileToPDF(report.Metafile, pdfFile, True, True);
      if not FileExists(pdfFile) then
      begin
        WriteLn('ERROR: PDF A/3 file was not generated: ', pdfFile);
        Exit;
      end;

      if FindFirst(pdfFile, faAnyFile, sr) = 0 then
      begin
        WriteLn('   PDF A/3 generated: ', pdfFile, ' (size: ', sr.Size, ' bytes)');
        FindClose(sr);
      end;

      pngFile := 'test_export_boldold.png';
      if FileExists(pngFile) then DeleteFile(pngFile);

      WriteLn('2. Exporting metafile to PNG via SaveMetafileToPNG...');
      count := SaveMetafileToPNG(report.Metafile, pngFile);
      WriteLn('   Exported pages count: ', count);
      if count < 1 then
      begin
        WriteLn('ERROR: SaveMetafileToPNG returned 0 pages.');
        Exit;
      end;

      if not FileExists(pngFile) then
      begin
        WriteLn('ERROR: PNG file not found: ', pngFile);
        Exit;
      end;

      // Verify PNG magic header ($89, 'P', 'N', 'G')
      FillChar(buf, SizeOf(buf), 0);
      fs := TFileStream.Create(pngFile, fmOpenRead);
      try
        fs.ReadBuffer(buf, 4);
        if (buf[0] <> $89) or (buf[1] <> Ord('P')) or (buf[2] <> Ord('N')) or (buf[3] <> Ord('G')) then
        begin
          WriteLn('ERROR: Generated file does not have valid PNG header.');
          Exit;
        end;
      finally
        fs.Free;
      end;

      if FindFirst(pngFile, faAnyFile, sr) = 0 then
      begin
        WriteLn('   PNG verified successfully (size: ', sr.Size, ' bytes)');
        FindClose(sr);
      end;

      report.EndPrint;
    finally
      driver.Free;
    end;
  finally
    report.Free;
  end;

  // Test multi-page export with sample4.rep
  repPath := FindReportFile('sample4.rep');
  if FileExists(repPath) then
  begin
    WriteLn('3. Testing multi-page export with sample4.rep...');
    report := TRpReport.Create(nil);
    try
      report.LoadFromFile(repPath);
      driver := TRpGDIDriver.Create;
      try
        report.BeginPrint(driver);
        report.Metafile.RequestPage(100);
        WriteLn('   sample4 total pages = ', report.Metafile.CurrentPageCount);

        pdfFile := 'test_export_sample4_a3.pdf';
        if FileExists(pdfFile) then DeleteFile(pdfFile);
        SaveMetafileToPDF(report.Metafile, pdfFile, True, True);
        if not FileExists(pdfFile) then
        begin
          WriteLn('ERROR: sample4 PDF A/3 was not generated.');
          Exit;
        end;
        WriteLn('   sample4 PDF A/3 created successfully.');

        pngFile := 'test_export_sample4.png';
        count := SaveMetafileToPNG(report.Metafile, pngFile);
        WriteLn('   sample4 PNG exported pages = ', count);
        if count <> report.Metafile.CurrentPageCount then
        begin
          WriteLn('ERROR: Exported page count mismatch: expected ', report.Metafile.CurrentPageCount, ', got ', count);
          Exit;
        end;

        if count > 1 then
        begin
          if not FileExists('test_export_sample4_1.png') then
          begin
            WriteLn('ERROR: test_export_sample4_1.png was not found.');
            Exit;
          end;
          WriteLn('   Multi-page naming pattern verified: test_export_sample4_1.png exists.');
        end;

        report.EndPrint;
      finally
        driver.Free;
      end;
    finally
      report.Free;
    end;
  end;

  Result := True;
end;

var
  passed, total: Integer;
begin
  Application.Initialize;

  passed := 0;
  total := 0;

  Inc(total);
  if TestSnapshot('firedactest.rep', 'snapshot_firedactest.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('sample4.rep', 'snapshot_sample4.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('bold.rep', 'snapshot_bold.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold.png', 1.0) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_110.png', 1.1) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_090.png', 0.9) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_050.png', 0.5) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_150.png', 1.5) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('boldold.rep', 'snapshot_boldold_200.png', 2.0) then
    Inc(passed);

  Inc(total);
  if TestSnapshot('arab2wordwrap.rep', 'snapshot_arab2wordwrap.png') then
    Inc(passed);

  Inc(total);
  if TestSnapshot('htmltest.rep', 'snapshot_htmltest.png') then
    Inc(passed);

  Inc(total);
  if TestPreviewFormInstantiation then
    Inc(passed);

  Inc(total);
  if TestMetafileExportPDFAndPNG then
    Inc(passed);

  WriteLn('==================================================');
  WriteLn(Format('LCL Visual Test Results: %d / %d PASSED', [passed, total]));
  WriteLn('==================================================');

  if passed = total then
    Halt(0)
  else
    Halt(1);
end.
